# =============================
# MAINNET
# =============================

[mainnet.bool]
is_l1 = true
deploy_layerzero_adapter = true
deploy_linea_adapter = true

[mainnet.address]
bridging_admin = "0x0000000000000000000000000000000000000000"
bridge_coordinator_roles_admin = "0x0000000000000000000000000000000000000000"
bridge_coordinator_adapter_manager = "0x0000000000000000000000000000000000000000"
bridge_coordinator_predeposit_manager = "0x0000000000000000000000000000000000000000"
layerzero_endpoint = "0x1a44076050125825900e736c501f859c50fE728c" # https://docs.layerzero.network/v2/deployments/deployed-contracts?chains=ethereum

# =============================
# CITREA
# =============================

[4114.bool]
is_l1 = false
deploy_layerzero_adapter = true
deploy_linea_adapter = false

[4114.address]
bridging_admin = "0x0000000000000000000000000000000000000000"
bridge_coordinator_roles_admin = "0x0000000000000000000000000000000000000000"
bridge_coordinator_adapter_manager = "0x0000000000000000000000000000000000000000"
layerzero_endpoint = "0x6F475642a6e85809B1c36Fa62763669b1b48DD5B" # https://docs.layerzero.network/v2/deployments/deployed-contracts?chains=citrea

# =============================
# SEPOLIA
# =============================

[sepolia.bool]
is_l1 = false
deploy_layerzero_adapter = true
deploy_linea_adapter = true

[sepolia.address]
bridging_admin = "0x0000000000000000000000000000000000000000"
bridge_coordinator_roles_admin = "0x0000000000000000000000000000000000000000"
bridge_coordinator_adapter_manager = "0x0000000000000000000000000000000000000000"
layerzero_endpoint = "0x6EDCE65403992e310A62460808c4b910D972f10f" # https://docs.layerzero.network/v2/deployments/deployed-contracts?chains=sepolia
